# -*- coding: utf-8 -*-
"""DSA Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-Y0v0izcSQm6N75KC6FD82YP162Wgn8

## 1. Complete the following code to find the area of an equilateral triangle. Output should be as displayed
"""

import math
side = float(input("Enter the side of the equilateral triangle: "))
area = ((math.sqrt(3))/4)*pow(side,2)
print('Area=',area)

"""## 2. Write a program to count the number of each characters in a string"""

string=input('enter the string: ')
for i in string:
  print(i, "=", string.count(i))

"""## Write a program to find the area and perimeter of a rectangle using functions"""

l=int(input("Length : "))
w=int(input("Width : "))
area=l*w
perimeter=2*(l+w)
print("Area of Rectangle : ",area)
print("Perimeter of Rectangle : ",perimeter)

"""## 4. Write a program to print the fibonacci series till a specified number"""

def fibonacci(num):
  if(num==0):
    return 0
  elif(num==1):
    return 1
  else:
    return (fibonacci(num-1)+fibonacci(num-2))
num=int(input("Enter a Limit:"))
i=0
while(i<num):
  print(fibonacci(i))
  i+=1

"""## 5. Complete the following code to find the minimum of 3 number using cinditional statements. Output should be as displayed"""

a,b,c = input("Enter three numbers followed by  : ").split()

print("First number :",a)
print("Second number :",b)
print("Third number :",c)
if(a==b==c):
    print("Entered numbers are equal!!!")
else:
  if(a<b and a<c):
    print(a," is smallest")
  elif b<c:
    print(b," is smallest")
  else:
    print(c," is smallest")

"""## 6. Write a program to print star pyramind. The number of rows should be taken as input from the user"""

num = int(input("Enter the number of rows"))
for i in range(1,num+1):
  for j in range(num-i):
     print(" " ,end="")
  for j in range(int(i)):
     print("*  ",end="")
  print("")

"""## 7. Complete the following code to convert hour into seconds. Output should be as displayed"""

def to_seconds(t):
    t=t*60*60
    return t
time_in_hours = int(input("Enter hours"))
print(time_in_hours ," Hour is equal to" ,to_seconds(time_in_hours) ," Seconds")

"""## 8. Write a program to print multiplication table as below"""

n=int(input("Enter a number to find the multiplication table:"))
for i in range(1,11):
  print(i,"*",n,"=",i*n)

"""## 9. Write a program to take your 5 favorite food as list and print each as 'I like Biriyani'"""

food=input("Enter your food list followed by space:").split()
for item in food:
  print("I like",item)

"""## 10. Find error(s) in the following code(if any) and rewrite code.


"""

x= int(input("Enter value of x:"))
for y in range(0,10):
     if x==y:
          print("They are equal")
     else:
         print( "They are unequal")

